
#  relay forward -b paypal http://localhost:8080/api/v1/webhook/gevent

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt-demo
    username: postgres
    password: roottcm123
#    url: jdbc:postgresql://viaduct.proxy.rlwy.net:34409/railway
#    username: postgres
#    password: '*DBG6352fg5f5*BCBC--EB2ddA36f2BE'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
#        ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

application:
  security:
    jwt:
      secret-key: 50352d383a2d3b256441505e5f7b242b2e695f52293e343776453e7d45
      expiration:  3600000 #an hour
      refresh-token:
        expiration:  43200000

mail:
  host: localhost
  port: 1025
  username: hello
  password: hello

  properties:
    mail:
      smtp:
        ssl:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 500
        timeout: 3000
        writetimeout: 5000


logging:
  level:
    org:
      springframework:
        security=DEBUG:
      hibernate=DEBUG:
      hibernate:
        SQL=DEBUG:
    web: debug

#admin keys
# these keys are for testing purposes only and expired,  use your own keys
stripe:
  public-key: pk_test_51OnxyHGZc9ClwVjjHWIBelZM7vHG24fDdmUmDRsQz1H8WjL1byYYmrWV6Z4M6pIkrnHRHCELVAyPu1cKtf0Rl8ob00lr7nN93t
  secret-key: sk_test_51OnxyHGZc9ClwVjj5M3k9yANNv7RjKs5AXsUBFJHkiF1JlGBnYI9luKpBkY6nOCABHQfn0HWh4woCmiSoD6nnIfM00h7XhTqVy

paypal:
    clientId: AWbhO2aZTZRaEmgmoqIpre4rzFOxBX8-5O8gRct63Fv2XtjNC-1wRoRj2jGyKPh8rTgcgldrIPDgTVRv
    clientSecret: ED4YdJOfaylr8m-qbQyXiO6VDvoMSEe6c8jHHxQBCbJu4O2zLf5CQfG79ZrB8MzCqm_4BW8SVEhvCY7O
    baseUrl: https://api-m.sandbox.paypal.com
